package com.planitfood.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.planitfood.enums.DishType;
import com.planitfood.typeConverters.DishTypeTypeConverter;
import com.planitfood.typeConverters.IngredientsTypeConverter;
import com.planitfood.typeConverters.QuantitiesTypeConverter;

import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@DynamoDBTable(tableName = "Dish")
public class Dish {
    private String id;
    @NotNull
    private String name;
    private String searchName;
    @NotNull
    private DishType dishType;
    private List<Ingredient> ingredients;
    private String notes;
    private Float cookingTime;
    private Map quantities;

    // Needed for DynamoDB
    public Dish() {
    }

    public Dish(String id) {
        this.id = id;
    }

    public Dish(String id, String name) {
        this.id = id;
        this.name = name;
        this.searchName = name.toLowerCase();
    }

    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public void setName(String name) {
        this.name = name;
        this.searchName = name.toLowerCase();
    }

    @DynamoDBIndexHashKey(attributeName = "SearchName", globalSecondaryIndexName = "SearchName-index")
    public String getSearchName() {
        return searchName;
    }

    @DynamoDBIndexHashKey(attributeName = "SearchName", globalSecondaryIndexName = "SearchName-index")
    public void setSearchName(String searchName) {
        this.searchName = searchName;
    }

    @DynamoDBTypeConverted(converter = IngredientsTypeConverter.class)
    @DynamoDBAttribute(attributeName = "Ingredients")
    public List<Ingredient> getIngredients() {
        return ingredients;
    }

    @DynamoDBTypeConverted(converter = IngredientsTypeConverter.class)
    @DynamoDBAttribute(attributeName = "Ingredients")
    public void setIngredients(List<Ingredient> ingredients) {
        this.ingredients = ingredients;
    }

    @DynamoDBIgnore
    public void addIngredient(Ingredient ingredient) {
        if (this.ingredients == null) {
            this.ingredients = new ArrayList<>();
        }
        this.ingredients.add(ingredient);
    }

    @DynamoDBAttribute(attributeName = "Notes")
    public String getNotes() {
        return notes;
    }

    @DynamoDBAttribute(attributeName = "Notes")
    public void setNotes(String notes) {
        this.notes = notes;
    }

    @DynamoDBAttribute(attributeName = "CookingTime")
    public Float getCookingTime() {
        return cookingTime;
    }

    @DynamoDBAttribute(attributeName = "CookingTime")
    public void setCookingTime(Float cookingTime) {
        this.cookingTime = cookingTime;
    }

    @DynamoDBTypeConverted(converter = DishTypeTypeConverter.class)
    @DynamoDBAttribute(attributeName = "DishType")
    public DishType getDishType() {
        return dishType;
    }

    @DynamoDBTypeConverted(converter = DishTypeTypeConverter.class)
    @DynamoDBAttribute(attributeName = "DishType")
    public void setDishType(DishType dishType) {
        this.dishType = dishType;
    }

    @JsonIgnore
    @DynamoDBAttribute(attributeName = "Quantities")
    @DynamoDBTypeConverted(converter = QuantitiesTypeConverter.class)
    public Map getQuantities() {
        return this.quantities;
    }

    @DynamoDBAttribute(attributeName = "Quantities")
    @DynamoDBTypeConverted(converter = QuantitiesTypeConverter.class)
    public void setQuantities(Map quantities) {
        this.quantities = quantities;
    }
}
