package com.planitfood.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;

@DynamoDBTable(tableName = "Meal")
public class MealWithFullDish {

    String id;
    @NotNull
    String name;
    String searchName;
    List<Dish> dishes;
    String notes;

    public MealWithFullDish() {
    }

    public MealWithFullDish(String id) {
        this.id = id;
    }

    public MealWithFullDish(String id, String name) {
        this.id = id;
        this.name = name;
        this.searchName = name.toLowerCase();
    }

    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public void setName(String name) {
        this.name = name;
        this.searchName = name.toLowerCase();
    }

    @DynamoDBIndexHashKey(attributeName = "SearchName", globalSecondaryIndexName = "SearchName-index")
    public String getSearchName() {
        return searchName;
    }

    @DynamoDBIndexHashKey(attributeName = "SearchName", globalSecondaryIndexName = "SearchName-index")
    public void setSearchName(String searchName) {
        this.searchName = searchName;
    }

    @DynamoDBIgnore
    public void addDish(Dish dish) {
        if (this.dishes == null) {
            this.dishes = new ArrayList<>();
        }

        this.dishes.add(dish);
    }

    @DynamoDBAttribute(attributeName = "Notes")
    public String getNotes() {
        return notes;
    }

    @DynamoDBAttribute(attributeName = "Notes")
    public void setNotes(String notes) {
        this.notes = notes;
    }

    @DynamoDBTypeConvertedJson
    public List<Dish> getDishes() {
        return dishes;
    }

    @DynamoDBTypeConvertedJson
    public void setDishes(List<Dish> dishes) {
        this.dishes = dishes;
    }
}
